#!/usr/bin/env bash
# configure an ubuntu server with nginx
ssh -v ubuntu@34.229.255.211
#install nginx and allow firewall
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start

#set redirection
REDIRECT="\n\tlocation /redirect_me {\n\t\treturn 301 https://youtu.be/dQw4w9WgXcQ;\n\t}\n"
FILE="/etc/nginx/sites-available/default"
sudo sed -i "42i\ $REDIRECT" "$FILE"

#set error display page
FORERROR="Ceci n'est pas une page"
ERRORFILE="/usr/share/nginx/html/404error.html"
ERRORREDIRECT="\n\terror_page 404 /404error.html;\n\tlocation = /404error.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"
echo "$FOUR" > "$ERRORFILE"
sudo sed -i "42i\ $ERRORREDIRECT" "$FILE"

#set http response header
CUSTOMHEADER='\n\tadd_header X-Served-By $hostname;\n'
sudo sed -i "42i\ $CUSTOMHEADER" "$FILE"

#restart nginx
sudo service nginx restart

