#!/usr/bin/env bash
# This script installs and sets up a load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown -R "$USER:$USER" /etc/haproxy/
printf %s "
#frontend configuration
frontend http-in
    bind *:80
    default_backend servers
# Backend configuration
backend servers
    balance roundrobin
    server server1 54.208.84.31
    server server2 54.172.141.180
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
