#!/usr/bin/env bash
# This script installs and sets up a load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown -R "$USER:$USER" /etc/haproxy/
printf %s "
#frontend configuration
frontend http-in
    bind *:80
    default_backend servers
# Backend configuration
backend servers
    balance roundrobin
    server server1 52.87.10.77 check
    server server2 34.229.255.211 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
