#!/usr/bin/env bash
# bash script that displays Best School 10 times and hi on the 9th loop with while loop
x=0
while [ $x -lt 10 ]
do
	if [[ $x -eq  3 ]]
	then
		echo "bad luck"
	elif [[ $x -eq 7 ]]
	then
		echo "good luck"
	else
		echo "Best School"
	fi

	(( x++ ))
done
