#!/usr/bin/env bash
# display 1-20 with cases for 4, 9 and 17
x=1
while [ $x -le 20 ]
do
	echo $x
	case $x in 
		"4")
			echo "bad luck from China"
			;;
		"9")
			echo "bad luck from Japan"
			;;
		"17")
			echo "bad luck from Italy"
			;;
	esac
	(( x++ ))
done	
