#!/usr/bin/env bash
# bash script that displays the time for 12hrs and 59 mins with while loop
x=0
while [ $x -le 12 ]
do
	echo "Hour: $x"
	y=1
	while [ $y -lt 60 ]
	do
		echo $y
		(( y++ ))
	done
	(( x++ ))
done
